// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVNm4j1gVfx3DnIjKLVZfTlVpa-97sg74',
    appId: '1:473666894846:web:db53db870d5fc83eb95eaf',
    messagingSenderId: '473666894846',
    projectId: 'pizza-delivery-2d5d2',
    authDomain: 'pizza-delivery-2d5d2.firebaseapp.com',
    storageBucket: 'pizza-delivery-2d5d2.appspot.com',
    measurementId: 'G-LRF9192PWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB2kaVPuI6ERwoOI6ZmJ22BQVOoW36ADk',
    appId: '1:473666894846:android:a4e3de785694515ab95eaf',
    messagingSenderId: '473666894846',
    projectId: 'pizza-delivery-2d5d2',
    storageBucket: 'pizza-delivery-2d5d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ChuWRcJd-54znSPhIorDuy5LXhbitdo',
    appId: '1:473666894846:ios:3bb7833a97f67165b95eaf',
    messagingSenderId: '473666894846',
    projectId: 'pizza-delivery-2d5d2',
    storageBucket: 'pizza-delivery-2d5d2.appspot.com',
    iosBundleId: 'com.example.shoppingapp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ChuWRcJd-54znSPhIorDuy5LXhbitdo',
    appId: '1:473666894846:ios:3bb7833a97f67165b95eaf',
    messagingSenderId: '473666894846',
    projectId: 'pizza-delivery-2d5d2',
    storageBucket: 'pizza-delivery-2d5d2.appspot.com',
    iosBundleId: 'com.example.shoppingapp01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVNm4j1gVfx3DnIjKLVZfTlVpa-97sg74',
    appId: '1:473666894846:web:0cbb76757db0b6fab95eaf',
    messagingSenderId: '473666894846',
    projectId: 'pizza-delivery-2d5d2',
    authDomain: 'pizza-delivery-2d5d2.firebaseapp.com',
    storageBucket: 'pizza-delivery-2d5d2.appspot.com',
    measurementId: 'G-G8JJ5F0VFK',
  );
}
